sample_app/config/routes.rb
Rails.application.routes.draw do
#これは対応表#設定情報に関するフォルダ
#get "URL" => "コントローラー名#アクション名"
	get 'posts/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get 'top' => 'root#top'

	post 'posts' => 'posts#create'
 #<a>タグで画面遷移する場合はget
 #<form>でデータを送信して画面遷移する場合にはpostを使用する

	get 'posts' => 'posts#index'
	get 'posts/:id' => 'posts#show', as: 'post'
  #.../posts/1や.../posts/3に該当する
  #'posts#show'の設定を「post」として利用できる意味
	get 'posts/:id/edit' => 'posts#edit', as: 'edit_post'

	patch 'posts/:id' => 'posts#update', as: 'update_post'
	delete 'posts/:id' => 'posts#destroy', as: 'destroy_post'
end

sample_app/app/models/post.rb
class Post < ApplicationRecord
    attachment :image
end

sample_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

sample_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def new
  		@post = Post.new
	end

	def create
        post = Post.new(post_params)
        post.save # DBへ保存する
        redirect_to post_path(post.id) # 詳細画面へリダイレクト
	end

    def index
    	@posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
    	post = Post.find(params[:id])
        post.update(post_params)
        redirect_to post_path(post.id)
    end

	def destroy
    	post = Post.find(params[:id])#データ(レコード)を1件取得
        post.destroy#レコードをDBから削除
        redirect_to posts_path#post一覧画面へリダイレクト
    end

      private
    def post_params
        params.require(:post).permit(:title, :body, :image)
    end

    
end

sample_app/app/controllers/root_controller.rb
class RootController < ApplicationController
	def top

	end


end

sample_app/app/helpers/posts_helper.rb
module PostsHelper
end

sample_app/app/helpers/root_helper.rb
module RootHelper
end

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

sample_app/app/views/posts/edit.html.erb
<h1>編集画面</h1>
<%= form_for(@post) do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <%= f.submit '保存' %>    
<% end %>

sample_app/app/views/posts/index.html.erb
<h1>投稿一覧</h1>
 <% @posts.each do |post| %>
    <p>タイトル</p>
    <span>
    	<%=link_to post.title, post_path(post.id) %>
    </span>
    <p>画像</p>
		<%= attachment_image_tag post, :image, :fill, 100, 100, format: 'jpeg' %>
<% end %>

sample_app/app/views/posts/new.html.erb
<h1>新規投稿</h1>
<!-- form_for部分 -->
<%= form_for(@post) do |f| %>

    <h4>タイトル</h4>
    <%= f.text_field :title %>

    <h4>本文</h4>
    <%= f.text_area :body %>

    <h4>画像</h4>
	<%= f.attachment_field :image %>

    <%= f.submit '投稿' %>

<% end %>

sample_app/app/views/posts/show.html.erb
<h2>タイトル</h2>
<p><%= @post.title %></p>
<h2>本文</h2>
<p><%= @post.body %></p>

<h2>画像</h2>
<%= attachment_image_tag @post, :image, :fill, 300, 300, format: 'jpeg' %>

<%= link_to "編集", edit_post_path(@post.id) %>
<%= link_to "削除", destroy_post_path(@post.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
 

sample_app/app/views/root/top.html.erb
<h1>ここはTOPページです</h1>